- name: deploy
  hosts: all
  become: yes
  vars:
    source_file: "./index.j2"
    destination_file: "/var/www/html"


  tasks:
    - name: install all deps (ubuntu)
      when: ansible_distribution == "Ubuntu"
      apt:
        name: nginx
        state: present

    - name: install all deps (centos)
      when: ansible_distribution == "CentOS"
      yum:
        name: nginx
        state: present
      
    - name: copying source files
      template:
        src: "{{ source_file }}"
        dest: "{{ destination_file }}/index.html"
      notify: restart nginx


  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
        enabled: yes
    




  